bind_host: 127.0.0.1
bind_port: 3000
dns:
  bind_hosts:
    - ${GW_TRUSTED}
    - ${WG_DNS}
  port: 53
  upstream_dns:
    # Encrypted upstreams (DoT) with Quad9 primary, Cloudflare secondary
    - tls://dns.quad9.net
    - tls://1.1.1.1
  bootstrap_dns:
    # Plain DNS used only to resolve DoT hostnames at startup
    - 9.9.9.9
    - 1.1.1.1
  protection_enabled: true
  filtering_enabled: true
  blocking_mode: default
  dnssec_enabled: true
  querylog_enabled: false
  anonymize_client_ip: true
