bind_host: 0.0.0.0
bind_port: 3000
dns:
  bind_hosts:
    - ${GW_TRUSTED}
    - ${WG_DNS}
  port: 53
  upstream_dns:
    - https://dns.quad9.net/dns-query
    - https://cloudflare-dns.com/dns-query
  bootstrap_dns:
    - 9.9.9.9
    - 1.1.1.1
  protection_enabled: true
  filtering_enabled: true
  blocking_mode: default
  dnssec_enabled: true
