# Rendered by 06_generate_router_configs.sh
network:
  version: 2
  renderer: networkd
  ethernets:
    ${ROUTER_WAN_IF}:
      # If using DHCP on WAN set dhcp4: true (default). For static, set dhcp4: false and fill addresses/gateway/nameservers.
      dhcp4: true
      optional: true
      # addresses: [${WAN_STATIC_IP}]
      # routes:
      #   - to: 0.0.0.0/0
      #     via: ${WAN_STATIC_GW}
      # nameservers:
      #   addresses: [${WAN_STATIC_DNS}]
    ${ROUTER_LAN_IF}:
      dhcp4: false
      accept-ra: false
  vlans:
    ${ROUTER_LAN_IF}.${VLAN_TRUSTED}:
      id: ${VLAN_TRUSTED}
      link: ${ROUTER_LAN_IF}
      addresses: [${GW_TRUSTED}/24]
    ${ROUTER_LAN_IF}.${VLAN_IOT}:
      id: ${VLAN_IOT}
      link: ${ROUTER_LAN_IF}
      addresses: [${GW_IOT}/24]
    ${ROUTER_LAN_IF}.${VLAN_GUEST}:
      id: ${VLAN_GUEST}
      link: ${ROUTER_LAN_IF}
      addresses: [${GW_GUEST}/24]
    ${ROUTER_LAN_IF}.${VLAN_LAB}:
      id: ${VLAN_LAB}
      link: ${ROUTER_LAN_IF}
      addresses: [${GW_LAB}/24]

# Enable IPv4 forwarding
ethtool:
  features: {}
