name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust:
    name: Rust fmt/clippy/build/test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Build server
        working-directory: home-secnet/router/spa-pq
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-targets -- -D warnings
          cargo build --release
          cargo test --all --release
      - name: Show workspace tree (debug)
        run: |
          pwd
          ls -la
          ls -la home-secnet || true
          ls -la home-secnet/clients || true
          find . -maxdepth 3 -type d -name 'spa-pq-client' -print || true
          test -f home-secnet/router/spa-pq/Cargo.toml && echo "server manifest OK" || echo "server manifest MISSING"
          test -f home-secnet/clients/spa-pq-client/Cargo.toml && echo "client manifest OK" || echo "client manifest MISSING"
      - name: Build client (manifest-path)
        run: |
          if [ -f home-secnet/clients/spa-pq-client/Cargo.toml ]; then
            cargo fmt --manifest-path home-secnet/clients/spa-pq-client/Cargo.toml --all -- --check
            cargo clippy --manifest-path home-secnet/clients/spa-pq-client/Cargo.toml --all-targets -- -D warnings
            cargo build --manifest-path home-secnet/clients/spa-pq-client/Cargo.toml --release
            cargo test --manifest-path home-secnet/clients/spa-pq-client/Cargo.toml --all --release || true
          else
            echo "Client crate manifest not found; skipping client build.";
          fi

  shell:
    name: Shell lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Shellcheck scripts
        run: |
          shopt -s globstar || true
          shellcheck -S warning home-secnet/scripts/**/*.sh home-secnet/tests/*.sh || true
