name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust:
    name: Rust fmt/clippy/build/test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Build server
        working-directory: home-secnet/router/spa-pq
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-targets -- -D warnings
          cargo build --release
          cargo test --all --release
      - name: Build client
        working-directory: home-secnet/clients/spa-pq-client
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-targets -- -D warnings
          cargo build --release
          cargo test --all --release || true

  shell:
    name: Shell lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Shellcheck scripts
        run: |
          shopt -s globstar || true
          shellcheck -S warning home-secnet/scripts/**/*.sh home-secnet/tests/*.sh || true

