name: ci

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install shellcheck and ripgrep
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck ripgrep

      - name: Run checks
        run: |
          make -C home-secnet checks-openwrt

