name: Secrets Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  gitleaks-working-tree:
    name: Gitleaks (working tree)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitleaks (workspace only)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  trufflehog-oss:
    name: TruffleHog OSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan with TruffleHog (verified only)
        uses: trufflesecurity/trufflehog@main
        with:
          scan: git
          extra_args: --only-verified --fail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
