name: Secrets Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  gitleaks-working-tree:
    name: Gitleaks (working tree)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitleaks (workspace only)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  gitleaks-history:
    name: Gitleaks (full history)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install gitleaks
        run: |
          GITLEAKS_VERSION=8.24.3
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz -o /tmp/gitleaks.tgz
          tar -xzf /tmp/gitleaks.tgz -C /usr/local/bin gitleaks
          gitleaks version
      - name: Run gitleaks (full history)
        run: |
          gitleaks detect --redact -v --exit-code=1 --report-format=sarif --report-path=results-history.sarif --source .
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results-history.sarif
